### ISSUE TITLE
Prevent selenium test when maven install or package

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-web-multi-blank#175]
## Description
Maven Install or package is failed because selenium test is executed.

## Possible Solutions
* Remove the projectName-selenium from module ?
* Add configuration for preventing test execution in the projectName-selenium ?
* Change to use maven-failsafe-plugin.
* etc ...

## Affects Version/s
* 5.1.0-SNAPSHOT

## Fix Version/s
- [x] 5.1.0

## Issue Links
* #130

**Comment by making** [comment]
maven-failsafe-plugin executes `**/*IT.java` tests.

* Rename `HelloTest` -> `HelloIT`
* Add maven-failsafe-plugin
* Exclude `**/*IT.java` in maven-surefire-plugin 

will work.

http://www.slideshare.net/nagaseyasuhito/extreme-opened-java-ee-devops/26
