### ISSUE TITLE
build-helper-maven-plugin doesn't work for adding auto-generated files 

### ISSUE THREAD

**Issue by kazato** [terasolunaorg/terasoluna-gfw-web-multi-blank#176]
## Description

For internal purpose, I want to use additional sources/resoureces folders such as `src/generated/java`, `src/generated/resources` in Maven modules generated from the archetype.  
build-helper-maven-plugin appears to be configured for this, but the plugin is never executed during  a Maven build.

## Possible Solutions
According to [the usage](http://www.mojohaus.org/build-helper-maven-plugin/usage.html) on build-helper-maven-plugin, the `<plugin>` tag should be placed under /project/build/plugins, rather than /project/build/pluginManagement/plugins in a pom.xml

Just removing (unwrapping) an extra `<pluginManagement>` tag in the parent pom.xml would fix the problem.

* https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/pom.xml#L70

## Affects Version/s
* 5.0.1.RELEASE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2

## Issue Links
* #112 add build-helper-maven-plugin for auto-generated files

**Comment by kazuki43zoo** [comment]
@kazato , thanks for report.

We added plugin configurations for adding auto-generated files at 5.0.1.RELEASE. However plugin is disabled by default.
If build-helper-maven-plugin use, you needs to add plugin setting at the project which use a plugin as follow:

**[pom.xml]**

```xml
<build>
    <plugins>
       <!-- ### ↓ start  -->
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
        </plugin>
       <!-- ### ↑ end  -->
    </plugins>
</build>
```

We will consider a default setting in next release(5.1.0 and 5.0.2).

**Comment by making** [comment]
agree

**Comment by ikeyat** [comment]
* Enable the plugin in modules that can have Java source code
    * web
    * domain
    * selenium
* Keep the definition at ``<pluginManagement>`` for define the plugin's version to be applied.

@kazato 
We will do that if you accept above.

**Comment by kazato** [comment]
@ikeyat
Thank you for considering my request.
I accept your solution :+1:

**Comment by ikeyat** [comment]
@btjinbotm 
Please add https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/176#issuecomment-144800200  ``<plugin>`` definition on these projects of multi-blank
* web
* domain
* selenium

**Comment by ikeyat** [comment]
@btfurukawatkr 
Please backport to 5.0.x

**Comment by ikeyat** [comment]
We don't care Single Blank Project for this.
