### ISSUE TITLE
Reflect changes of MyBatis 3.3.0

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-web-multi-blank#178]
## Description
Define the `defaultFetchSize` as same with JPA project in MyBatis project.

**Note:**
`defaultFetchSize` parameter is supported at MyBatis 3.3.0.

## Possible Solutions
Add setting as follow:

```xml
<setting name="defaultFetchSize" value="100" />
```

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0

## Issue Links
* terasolunaorg/guideline#965

**Comment by btshimizukza** [comment]
Please change [default value](https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/infra/mybatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml#L15) of `proxyFactory` settings. (`JAVASSIST` -> `CGLIB`).
At MyBatis 3.3.0 or later version, `proxyFactory` is used `JAVASSIST` by default. (`CGLIB` is default value in 3.2.x series)
