### ISSUE TITLE
Apply Spring IO Platform 2.0

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-web-multi-blank#195]
## Description
Apply changes of Spring IO Platform 2.0.

* terasolunaorg/terasoluna-gfw#362
* terasolunaorg/guideline#1305 (Japanese only)

## Fix Version/s
- [ ] 5.1.0

## Issue Links
N/A

**Comment by iwanagah** [comment]
It found that there is no need to change by @btokadanob 's research.
