### ISSUE TITLE
Add "<sec:logout/>"

### ISSUE THREAD

**Issue by btsatoutkzy** [terasolunaorg/terasoluna-gfw-web-multi-blank#207]
## Description
Add "<sec:logout/>".

## Possible Solutions
 * Add "<sec:logout/>" to spring-security.xm

## Fix Version/s
- [ ] 5.1.0

## Issue Links
N/A

**Comment by kazuki43zoo** [comment]
@btsatoutkzy 

Please resolve with #201.
