### ISSUE TITLE
Typo in spring-mvc.xml 

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-web-multi-blank#281]
## Description
There is a typo in `spring-mvc.xml`

see https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml#L25.

## Possible Solutions

`workarround` > `workaround`

## Affects Version/s
* 5.2.0.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

## Issue Links
\-

**Comment by btyoshikawaa** [comment]
Let's correspond all versions, it is easy.
