### ISSUE TITLE
Warning about Logback.xml appears in Eclipse.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-web-multi-blank#332]
## Description
In Eclipse (I confirmed in STS), warning about Logback.xml appears.
```text
warning : No grammar constraints (DTD or XML schema) detected for the document.
```

## Possible Solutions
See [stackoverflow](https://stackoverflow.com/questions/5731162/xml-schema-or-dtd-for-logback-xml#14025514).
I think it's better to avoid warnings by adding DOCTYPE ex, `<!DOCTYPE xml>`.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.2 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Final Solution
https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/a0e5b933abde956da431f1ca0fbc9eaba3339e56/projectName-env/src/main/resources/logback.xml#L1-L2
```diff
<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE configuration>
<configuration>
```

## Migrating Guide
* Required
  * ( Changes the blank project List )

## Issue Links
* terasolunaorg/terasoluna-gfw-web-blank#299
* terasolunaorg/terasoluna-tourreservation#509

**Comment by itouyun** [comment]
I see. We will do.

**Comment by yoshikawaa** [comment]
@itouyun
Yes also. Please see https://github.com/terasolunaorg/terasoluna-gfw-web-blank/blob/master/src/main/resources/logback.xml#L2 .

**Comment by kazuki43zoo** [comment]
Probably `<!DOCTYPE configuration>` is proper more as role of DOCTYPE.

**Comment by itouyun** [comment]
@kazuki43zoo 
Why `configuration` is more proper than `xml`?
-> Ref is this? : https://stackoverflow.com/questions/5731162/xml-schema-or-dtd-for-logback-xml#comment19432392_5731162

- XML Standards Reference
  - Ja: https://msdn.microsoft.com/ja-jp/library/ms256059.aspx
  - En: https://msdn.microsoft.com/en-us/library/ms256059.aspx

Is `configuration` that the name of the document or root element?

**Comment by kazuki43zoo** [comment]
> Is configuration that the name of the document or root element?

yes.

**Comment by itouyun** [comment]
I update Final Solution.

**Comment by itouyun** [comment]
@btoutnp 
Thank you for your work!

**Comment by btyanagawamg** [comment]
add backport for all versions(before 5.2.x) .
