### ISSUE TITLE
Should define the dependency to older version Selenium in blank project?

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-web-multi-blank#333]
## Description
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Overview/FrameworkStack.html#oss
Selenium is not on TERASOLUNA's OSS libraries stack.

I think... it is not a good idea to default to the version older than the version managed by Spring IO Platform.
_(Because Selenium and the browser version are deeply involved, in the actual development scene, the old Selenium is used less often)_

## Possible Solutions
Remove or adjust to Spring IO Platform the definition `selenium.version`.
_(The latter has an advantage that it is easier to change according to the responsibility of the TERASOLUNA user)_
```xml
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-java</artifactId>
  <version>${selenium.version}</version>
</dependency>
...
<selenium.version>2.46.0</selenium.version>
```
And remove the definition after `selenium-chrome-driver`.
_(This is defined to avoid the problem caused by the difference between the version managed by Spring IO Platform and the version defined by TERASOLUNA)_
```xml
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-chrome-driver</artifactId>
  <version>${selenium.version}</version>
</dependency>
...
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-support</artifactId>
  <version>${selenium.version}</version>
</dependency>
```

Or... use the newest Selenium?

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0.RELEASE
- [x] 5.3.1.RELEASE
- [x] 5.2.2.RELEASE -- not need to apply

## Issue Links
* #XXX

**Comment by itouyun** [comment]
@yoshikawaa 
Are there 4 solutions?
- Remove the definition `selenium.version` on blank project.
  - Should we guide the setting of Selenium on Guideline?
- Adjust to Spring IO Platform the definition `selenium.version` on blank project.
  - We should test `Spring IO Platform the definition` version.
- Set the newest Selenium version definition `selenium.version` on blank project.
  - We should test `Spring IO Platform the definition` version.
- Add Selenium version "2.46.0" on TERASOLUNA's OSS libraries stack on Guideline.

**Comment by yoshikawaa** [comment]
@itouyun 
Yeah, and I recommend 1st or 2nd solution until we start to support the E2E test at our guideline.

**Comment by itouyun** [comment]
We will 1st solution `Remove the definition selenium.version on blank project.` on Milestone of 2018 winter.
E2E test guideline is nothing now.

And future, 2nd solution is same time with starting to support the E2E test at our guideline. 2nd solution is done for another backlog issue.

**Comment by kazuki43zoo** [comment]
👍 

And.... I propose adding the comment that indicates needing to adjust the selenium version by requirements of the browser at `pom.xml` of projectName-selenium module.

**Comment by btyanagawamg** [comment]
@yoshikawaa 

In 5.2.x version, used Spring IO Platform version is [2.0.6.RELEASE](https://github.com/terasolunaorg/guideline/blame/5.2.x/source/Overview/FrameworkStack.rst#L138), but 2.0.6.RELEASE version does not define [`selenium-java`](https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/projectName-selenium/pom.xml#L65-L69) version.
https://docs.spring.io/platform/docs/2.0.6.RELEASE/reference/htmlsingle/
So in 5.2.x version, dependencyManagement must not remove.
