### ISSUE TITLE
Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security

### ISSUE THREAD

**Issue by hosoitk** [terasolunaorg/terasoluna-gfw-web-multi-blank#348]
## Description
Even if request path include ``.html``, interceptors should work.

## Possible Solutions
to delete below.
<mvc:exclude-mapping path="/**/*.html" />

## Affects Version/s
* 5.0.0.RELEASE and later
* 1.0.0.RELEASE and later

## Fix Version/s
 - [x] 5.5.0(master)
 - [x] 5.4.x
 - [x] 5.3.x
 - [x] 5.2.x
 - [x] 5.1.x
 - [x] 5.0.x
 - [x] 1.0.x
 - [x] 1.6.0 (m-j/)
 - [x] 1.5.x (m-j/)
 - [x] 1.4.x (m-j/)
 - [x] 1.6.0 (m-t/)
 - [x] 1.5.x (m-t/)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* none

**Comment by yoshikawaa** [comment]
Do you mean the behavior when you assign `.html` to the path mapped to Controller?
If so, I think so too.

Ex: request mapping is `sample/form`.
* normal request path `http://xxx.com/sample/form` -> interceptor work.
* extended request path `http://xxx.com/sample/form.html` -> **interceptor not work!**
