### ISSUE TITLE
Repository Privatization[JSP]

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-web-multi-blank#358]
## Description
Repository Privatization[JSP]

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] master
- [x] 5.3.x

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
#381
