### ISSUE TITLE
Repository Privatization[Thymeleaf]

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-web-multi-blank#359]
## Description
Repository Privatization[Thymeleaf]

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] master

## Final Solution
(To be written later by project member)

## Migrating Guide
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
see #381

**Comment by btyanagawamg** [comment]
## Fix URL
- [ ] master

**Comment by btyanagawamg** [comment]
We reopened this ISSUE by mistake.
I will close it.
