### ISSUE TITLE
define maven-surefire-plugin version

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-web-multi-blank#371]
## Description
define maven-surefire-plugin version match to [terasoluna-gfw definition](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/pom.xml#L157) .
`<maven-surefire-plugin.version>2.17</maven-surefire-plugin.version>`

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.2(+ private(JSP))
- [x] 5.2.2
- [ ] 5.1.2
- [ ] 5.0.3
- [ ] 1.0.7
※1.0.xおよび5.0.xはseleniumのpom.xmlにmaven-surefire-pluginが定義されておらず、バージョンの記載も必要ないので、対応不要

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by bttakahashikkr** [comment]
1.0.xおよび5.0.xはseleniumのpom.xmlにmaven-surefire-pluginが定義されておらず、バージョンの記載も必要ないので、本Issuesの対応は不要です。

**Comment by yoshikawaa** [comment]
@bttakahashikkr 
Please remove PR branch ( #383 ), and close this.
