### ISSUE TITLE
[Windows OS environment] WARNING occured when running resources-plugin

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-web-multi-blank#373]
## Description
[Windows OS environment]WARNING occured when running resources-plugin .
```console
[WARNING] Using platform encoding (MS932 actually) to copy filtered resources, i.e. build is platform dependent!
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
When we unify the source code to UTF-8+LF, you should know that this is an inevitable event.
