### ISSUE TITLE
Update version in README.md (2018 winter) 

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw-web-multi-blank#398]
## Description
Update version in master, 5.4.x, and 5.3.x

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0 (master)
- [x] 5.4.1 (5.4.x)
- [ ] 5.3.3 (5.3.x)
- [ ] 1.6.0 (m-j/master)
- [ ] 1.5.1 (m-j/1.5.x)
- [ ] 1.4.3 (m-j/1.4.x)
- [ ] 1.6.0 (m-t/master)
- [ ] 1.5.1 (m-t/1.5.x)
- [ ] 1.4.3 (m-t/1.4.x)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@btkobayashirun 
Re-work required for 5.5, 5.4.
Please See https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/pull/402#issuecomment-356521642.
