### ISSUE TITLE
[Postgresql 10] Upgrade Postgresql JDBC

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw-web-multi-blank#420]
## Description
Update the driver version to use postgresql 10.

## Possible Solutions
postgresql version 
9.4.1212.jre7 to 42.2.2

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0.RC2-SNAPSHOT (master)
- [x] 1.6.0.RC2-SNAPSHOT (m-j)
- [ ] 1.6.0.RC2-SNAPSHOT (m-t)

## Final Solution
TBD

## Migrating Guide
* Not Required

## Issue Links
*

**Comment by bttakahashikkr** [comment]
m-t については #436 にて対応済みのため、クローズする。
