### ISSUE TITLE
[Selenium 3.0] Update from Selenium 2 to Selenium 3

### ISSUE THREAD

**Issue by btkawamotosn** [terasolunaorg/terasoluna-gfw-web-multi-blank#433]
## Description
Update selenium ver 2 to 3.

## Possible Solutions
- Update Selenium version to `3.0.1`

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.x(master)
- [x] 1.6.0(m-j)
- [x] 1.6.0(m-t)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
see https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/382#issuecomment-459187358
