### ISSUE TITLE
Remove redundant version definitions for excluding libraries.

### ISSUE THREAD

**Issue by hirakuriy** [terasolunaorg/terasoluna-gfw-web-multi-blank#456]
## Description
There are redundant version definitions for excluding libraries in m-t.

## Possible Solutions
Remove redundant version definitions for excluding libraries.

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 1.7.0 (m-t/master)
- [x] 1.6.2 (m-t/1.6.x)
- [x] 1.5.2 (m-t/1.5.x)

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@btiwahorisu You should change version value to `${terasoluna.gfw.version}` to override dependency management.
```xml
            <dependency>
                <groupId>org.terasoluna.gfw</groupId>
                <artifactId>terasoluna-gfw-jodatime-dependencies</artifactId>
                <version>${terasoluna.gfw.version}</version>
                <type>pom</type>
                <exclusions>
                    <exclusion>
                        <groupId>joda-time</groupId>
                        <artifactId>joda-time-jsptags</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```
