### ISSUE TITLE
Update version in master, 5.5.x, and 5.4.x

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-web-multi-blank#459]
## Description
Update README version in master, 5.5.x, and 5.4.x

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.6.0 (master)
- [x] 5.5.1 (5.5.x)
- [x] 5.4.2 (5.4.x)

## Issue Links
- https://github.com/terasolunaorg/terasoluna-gfw/issues/913
- https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/406

**Comment by yoshikawaa** [comment]
@hirakuriy @btiwahorisu 
5.6.0.RELEASE has not been released yet!
Please change version of README.md to 5.5.1.RELEASE!
