### ISSUE TITLE
Reflect: Remove log4jdbc-remix

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw-web-multi-blank#469]
## Description
- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/947

## Possible Solutions
TBD

## Affects Version/s
- 5.6.0.RELEASE

## Fix Version/s
- [x] terasoluna-gfw-web-multi-blank
- [x] m-j
- [x] m-t

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
Reflect: https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/417#issuecomment-600990201
