### ISSUE TITLE
Javadoc generation fails when building with JDK 11

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-web-multi-blank#493]
## Description

Javadoc generation fails when building with JDK 11.
For example, the terasoluna-tourreservation displays the following error:

```console
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:javadoc (default-cli) on project terasoluna-tourreservation-domain: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - javadoc: エラー - ドキュメント化しようとしているコードではモジュールが使用されていますが、http://docs.oracle.com/javase/8/docs/api/で定義されているパッケージは名前のないモジュールのものです。
```

The cause is in the plugin settings of terasoluna-gfw-parent.
https://github.com/terasolunaorg/terasoluna-gfw/blob/4aae4e0782cee5e0a5848f36b3a1e773761de7e6/terasoluna-gfw-parent/pom.xml#L97-L107

To resolve, you need to specify the Javadoc source version.
https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#source

## Affect versions

- 5.6.0.RELEASE

## Fix repositories

- [x] terasoluna-gfw-web-multi-blank
- [x] m-j
- [x] m-t

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
This problem has been solved by the correspondence of https://github.com/terasolunaorg/terasoluna-gfw/issues/1010 and https://github.com/terasolunaorg/terasoluna-gfw/issues/1061.

**Comment by btkatoufm** [comment]
The behavior differs depending on the version of Java used, and the problem has not been resolved yet, so it will be reopened.
