### ISSUE TITLE
Reflect:Warning about accessing `java.util.TreeMap.comparator` is displayed.

### ISSUE THREAD

**Issue by btootomoyuk** [terasolunaorg/terasoluna-gfw-web-multi-blank#496]
We've decided to use a different issue to handle this. https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/514

## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/443

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

When I execute `mvn package`, the following warning is displayed.

```console
[INFO] --- maven-war-plugin:2.5:war (default-war) @ maven-test ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.collections.TreeMapConverter (file:/C:/Users/xxxxx/.m2/repository/com/thoughtworks/xstream/xstream/1.4.4/xstream-1.4.4.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.converters.collections.TreeMapConverter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Environments:
* OpenJDK 11.0.5
* Maven 3.5.4
* Maven War Plugin 2.5

Related?
* https://github.com/x-stream/xstream/issues/101
* https://bugster.forgerock.org/jira/browse/OPENIG-3895

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Update your plugins to the latest version

## Fix repositories
> Repositories to fix with this issue.

- [ ] terasoluna-gfw-web-multi-blank
- [ ] m-j
- [ ] m-t

**Comment by btkatoufm** [comment]
This issue has been resolved at https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/514.
