### ISSUE TITLE
Reflect:Update the version of maven-plugin

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw-web-multi-blank#546]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/1083

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Take the following actions:
- Upgrade the plugin version
- Modify the variable name of the plugin version to be `groupId.artifactId.pugin.version`.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-gfw-web-multi-blank
- [x] m-j
- [x] m-t

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/893#discussion_r672153131
The above comment says that you should consider setting it with proerty, but what about setting it as "multi-blank"?

As a countermeasure,
1. Define only in initdb as it is (unmodified)
2. Set the plugin in the root pluginManagement and use it with initdb
I think there are two possibilities.

**Comment by btonokit** [comment]
> [terasolunaorg/terasoluna-gfw-functionaltest#893 (comment)](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/893#discussion_r672153131)
> The above comment says that you should consider setting it with proerty, but what about setting it as "multi-blank"?
> 
> As a countermeasure,
> 
> 1. Define only in initdb as it is (unmodified)
> 2. Set the plugin in the root pluginManagement and use it with initdb
> 
> I think there are two possibilities.

- sql-maven-plugin only used with initdb
- Setting sql-maven-plugin in root plugin Management makes it complicated

From the above, I think that the measure of "2" is good.

**Comment by btkatoufm** [comment]
> Setting sql-maven-plugin in root plugin Management makes it complicated

Just because you manage it with pluginManagement doesn't mean it's complicated.
I think that "complexity" here means that changing "multi-blank" affects other repositories created based on "multi-blank", and it is difficult to change and confirm.
Do you match?

**Comment by btonokit** [comment]
> Do you match?

My expression was a little wrong.
If I take the measure of "2", it will be complicated when I change the setting of sql-maven-plugin of "multi-blank" in the future. As a result, it affects other repositories created based on "multi-blakn", making it difficult to change and check.

**Comment by btkatoufm** [comment]
OK. I understood it with a plan that does not correspond.
