### ISSUE TITLE
Reflect: Replace @RequestMapping with @GetMapping or @PostMapping

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw-web-multi-blank#550]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/502

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Replace `@RequestMapping` with `@GetMapping` or `@PostMapping`, which is highly readable and does not accept extra request methods.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

In the blank project, `@RequestMapping` is used as the controller to the top page. There, both Get and Post methods are used for mapping, but since Get alone seems to be sufficient, `@GetMapping` is used.

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-gfw-web-multi-blank
- [x] m-j
- [x] m-t

## Issue links
> Links to related issues.

- #xx

**Comment by btiwahorisu** [comment]
Closing this as I made the following changes:
https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/594
